name: Discord Notifications

on:
  push:
    branches:
      - "*"

jobs:
  create-notification:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.create_embed.outputs.embed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create Discord embed
        id: create_embed
        run: |
          node_exec=$(node create-discord-embed.js)
          echo "embed=$node_exec" >> $GITHUB_OUTPUT

  send-notification:
    runs-on: ubuntu-latest
    needs: create-notification
    steps:
      - env:
          EMBED: ${{needs.create-notification.outputs.output1}}
        run: echo "$EMBED"

      - name: Discord notification
        env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: ${{ {"embeds":[{"author":{"name":"jpedro002","url":"https://avatars.githubusercontent.com/u/122836400?v=4"},"description":"acabou de ter um pull request aceito! Parabéns! Continue assim.","color":15468499}]} }}
        uses: Ilshidur/action-discord@master
          
        
