name: Discord Notifications

on:
  push:
    branches:
      - "*"

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create Discord embed
        id: create_embed
        run: |
          node_exec=$((node create-discord-embed.js))
          echo "handle=$node_exec" >> "$GITHUB_OUTPUT"
      
      - name: log discord embed
        id: log_create_embed
        run: echo "${{ steps.create_embed.outputs.handle }}"

      # - name: Discord notification
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #     DISCORD_EMBEDS: ${{ steps.create_embed.outputs.value}}
      #   uses: Ilshidur/action-discord@master
        
