name: Discord Notifications

on:
  push:
    branches:
      - '*'

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Get commit message
      id: get_commit_message
      run: |
        commit_message=$(jq -r '.commits[0].message' $GITHUB_EVENT_PATH)
        echo "::set-output name=commit_message::$commit_message"

    - name: Create Discord embed
      id: create_embed
      run:  node create-discord-embed.js

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: ${{ toJson(steps.create_embed.outputs.embed) }}
        args: "Commit Merged: ${{ steps.get_commit_message.outputs.commit_message }}"
      uses: Ilshidur/action-discord@master
