name: Discord Notifications

on:
  push:
    branches:
      - '*'

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Create Discord embed
      id: create_embed
      run: |
        output=$(node create-discord-embed.js)
        echo "CREATE_EMBED=$(output)" >> "$GITHUB_OUTPUT"
        echo "$output"

    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_EMBEDS: ${{ steps.create_embed.outputs.CREATE_EMBED}}
      uses: Ilshidur/action-discord@master
