name: Discord Notifications

on:
  push:
    branches:
      - "*"

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{toJson({"embeds":[{"title":"Hello!","description":"Hi! :grinning:"}]})}}
        uses: Ilshidur/action-discord@master
