name: Discord Notifications

on:
  pull_request:
    types: [closed]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR was merged
      id: pr_check
      run: echo "::set-output name=merged::${{ github.event.pull_request.merged }}"
    
    - name: Create Discord embed
      id: create_embed
      run: echo "::set-output name=embed::$(node create-discord-embed.js)"

    - name: Send Discord notification
      if: steps.pr_check.outputs.merged == 'true'
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DISCORD_EMBED: ${{ steps.create_embed.outputs.embed }}
      uses: Ilshidur/action-discord@master
